version: '3.7'
services:
  node-devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - try-node:/home/node
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true

volumes:
  try-node:
